
from abcd_record import *

column_labels_text = ["ExperimentName",
                      "Subject",
                      "Session",
                      "Allowed",
                      "Clock.Information",
                      "DataFile.Basename",
                      "Display.RefreshRate",
                      "ExperimentVersion",
                      "Group",
                      "Handedness",
                      "IntNewRT",
                      "NARGUID",
                      "NewRT",
                      "ProbeDuration",
                      "RandomSeed",
                      "RuntimeCapabilities",
                      "RuntimeVersion",
                      "RuntimeVersionExpected",
                      "SessionDate",
                      "SessionStartDateTimeUtc",
                      "SessionTime",
                      "StudioVersion",
                      "Block",
                      "BlockTitle",
                      "IFISBlockList",
                      "IFISBlockList.Cycle",
                      "IFISBlockList.Sample",
                      "Instruction1",
                      "Instruction2",
                      "ListName",
                      "NameOfPeriodList",
                      "Periods",
                      "Procedure[Block]",
                      "Running[Block]",
                      "Task",
                      "TimingBlockList",
                      "TimingBlockList.Cycle",
                      "TimingBlockList.Sample",
                      "Trial",
                      "PeriodList",
                      "PeriodList.Cycle",
                      "PeriodList.Sample",
                      "PeriodListTiming",
                      "PeriodListTiming.Cycle",
                      "PeriodListTiming.Sample",
                      "Procedure[Trial]",
                      "Running[Trial]",
                      "SubTrial",
                      "Anticipation.RESP",
                      "Condition",
                      "Cue",
                      "LoseBig",
                      "LoseSmall",
                      "Neutral",
                      "prbacc",
                      "Probe",
                      "Probe.ACC",
                      "Probe.DurationError",
                      "Probe.OnsetDelay",
                      "Probe.OnsetTime",
                      "Probe.OnsetToOnsetTime",
                      "Probe.RESP",
                      "Probe.RT",
                      "Procedure[SubTrial]",
                      "ResponseCheck",
                      "Result",
                      "RunList",
                      "RunList.Cycle",
                      "RunList.Sample",
                      "RunListTiming",
                      "RunListTiming.Cycle",
                      "RunListTiming.Sample",
                      "Running[SubTrial]",
                      "WinBig",
                      "WinSmall"]


record = AbcdRecord("C:\Users\Allen W. Ingling\Desktop", "test_mid_output", column_labels_text)
record.save()



